/**
 * Mandatory includes
 *
 */
#include "types.h"
#include "kernel.h"
#include "idt2.h"

/**
 * Additional includes
 *
 */
#include "segment.h"
#include "utils.h"

/* IDT descriptors must be qword-aligned (8 bytes alignement). */
static uint64_t		_idt[IDT_N] __attribute__ ((aligned(8))); // auto alignée ?


/**
 * idt_init():
 *
 */
int32_t			idt_init(void)
{
  /* Populate the IDT with INTERRUPT GATE descriptors. */
  //  IDT_ADD_DESCRIPTORS();

  IDT_ADD_DESCRIPTOR(0);
  IDT_ADD_DESCRIPTOR(1);
  IDT_ADD_DESCRIPTOR(2);
  IDT_ADD_DESCRIPTOR(3);
  IDT_ADD_DESCRIPTOR(4);
  IDT_ADD_DESCRIPTOR(5);
  IDT_ADD_DESCRIPTOR(6);
  IDT_ADD_DESCRIPTOR(7);
  IDT_ADD_DESCRIPTOR(8);
  IDT_ADD_DESCRIPTOR(9);
  IDT_ADD_DESCRIPTOR(10);
  IDT_ADD_DESCRIPTOR(11);
  IDT_ADD_DESCRIPTOR(12);
  IDT_ADD_DESCRIPTOR(13);
  IDT_ADD_DESCRIPTOR(14);
  IDT_ADD_DESCRIPTOR(15);
  IDT_ADD_DESCRIPTOR(16);
  IDT_ADD_DESCRIPTOR(17);
  IDT_ADD_DESCRIPTOR(18);
  IDT_ADD_DESCRIPTOR(19);
  IDT_ADD_DESCRIPTOR(20);
  IDT_ADD_DESCRIPTOR(21);
  IDT_ADD_DESCRIPTOR(22);
  IDT_ADD_DESCRIPTOR(23);
  IDT_ADD_DESCRIPTOR(24);
  IDT_ADD_DESCRIPTOR(25);
  IDT_ADD_DESCRIPTOR(26);
  IDT_ADD_DESCRIPTOR(27);
  IDT_ADD_DESCRIPTOR(28);
  IDT_ADD_DESCRIPTOR(29);
  IDT_ADD_DESCRIPTOR(30);
  IDT_ADD_DESCRIPTOR(31);
  IDT_ADD_DESCRIPTOR(32);
  IDT_ADD_DESCRIPTOR(33);
  IDT_ADD_DESCRIPTOR(34);
  IDT_ADD_DESCRIPTOR(35);
  IDT_ADD_DESCRIPTOR(36);
  IDT_ADD_DESCRIPTOR(37);
  IDT_ADD_DESCRIPTOR(38);
  IDT_ADD_DESCRIPTOR(39);
  IDT_ADD_DESCRIPTOR(40);
  IDT_ADD_DESCRIPTOR(41);
  IDT_ADD_DESCRIPTOR(42);
  IDT_ADD_DESCRIPTOR(43);
  IDT_ADD_DESCRIPTOR(44);
  IDT_ADD_DESCRIPTOR(45);
  IDT_ADD_DESCRIPTOR(46);
  IDT_ADD_DESCRIPTOR(47);
  IDT_ADD_DESCRIPTOR(48);
  IDT_ADD_DESCRIPTOR(49);
  IDT_ADD_DESCRIPTOR(50);
  IDT_ADD_DESCRIPTOR(51);
  IDT_ADD_DESCRIPTOR(52);
  IDT_ADD_DESCRIPTOR(53);
  IDT_ADD_DESCRIPTOR(54);
  IDT_ADD_DESCRIPTOR(55);
  IDT_ADD_DESCRIPTOR(56);
  IDT_ADD_DESCRIPTOR(57);
  IDT_ADD_DESCRIPTOR(58);
  IDT_ADD_DESCRIPTOR(59);
  IDT_ADD_DESCRIPTOR(60);
  IDT_ADD_DESCRIPTOR(61);
  IDT_ADD_DESCRIPTOR(62);
  IDT_ADD_DESCRIPTOR(63);
  IDT_ADD_DESCRIPTOR(64);
  IDT_ADD_DESCRIPTOR(65);
  IDT_ADD_DESCRIPTOR(66);
  IDT_ADD_DESCRIPTOR(67);
  IDT_ADD_DESCRIPTOR(68);
  IDT_ADD_DESCRIPTOR(69);
  IDT_ADD_DESCRIPTOR(70);
  IDT_ADD_DESCRIPTOR(71);
  IDT_ADD_DESCRIPTOR(72);
  IDT_ADD_DESCRIPTOR(73);
  IDT_ADD_DESCRIPTOR(74);
  IDT_ADD_DESCRIPTOR(75);
  IDT_ADD_DESCRIPTOR(76);
  IDT_ADD_DESCRIPTOR(77);
  IDT_ADD_DESCRIPTOR(78);
  IDT_ADD_DESCRIPTOR(79);
  IDT_ADD_DESCRIPTOR(80);
  IDT_ADD_DESCRIPTOR(81);
  IDT_ADD_DESCRIPTOR(82);
  IDT_ADD_DESCRIPTOR(83);
  IDT_ADD_DESCRIPTOR(84);
  IDT_ADD_DESCRIPTOR(85);
  IDT_ADD_DESCRIPTOR(86);
  IDT_ADD_DESCRIPTOR(87);
  IDT_ADD_DESCRIPTOR(88);
  IDT_ADD_DESCRIPTOR(89);
  IDT_ADD_DESCRIPTOR(90);
  IDT_ADD_DESCRIPTOR(91);
  IDT_ADD_DESCRIPTOR(92);
  IDT_ADD_DESCRIPTOR(93);
  IDT_ADD_DESCRIPTOR(94);
  IDT_ADD_DESCRIPTOR(95);
  IDT_ADD_DESCRIPTOR(96);
  IDT_ADD_DESCRIPTOR(97);
  IDT_ADD_DESCRIPTOR(98);
  IDT_ADD_DESCRIPTOR(99);
  IDT_ADD_DESCRIPTOR(100);
  IDT_ADD_DESCRIPTOR(101);
  IDT_ADD_DESCRIPTOR(102);
  IDT_ADD_DESCRIPTOR(103);
  IDT_ADD_DESCRIPTOR(104);
  IDT_ADD_DESCRIPTOR(105);
  IDT_ADD_DESCRIPTOR(106);
  IDT_ADD_DESCRIPTOR(107);
  IDT_ADD_DESCRIPTOR(108);
  IDT_ADD_DESCRIPTOR(109);
  IDT_ADD_DESCRIPTOR(110);
  IDT_ADD_DESCRIPTOR(111);
  IDT_ADD_DESCRIPTOR(112);
  IDT_ADD_DESCRIPTOR(113);
  IDT_ADD_DESCRIPTOR(114);
  IDT_ADD_DESCRIPTOR(115);
  IDT_ADD_DESCRIPTOR(116);
  IDT_ADD_DESCRIPTOR(117);
  IDT_ADD_DESCRIPTOR(118);
  IDT_ADD_DESCRIPTOR(119);
  IDT_ADD_DESCRIPTOR(120);
  IDT_ADD_DESCRIPTOR(121);
  IDT_ADD_DESCRIPTOR(122);
  IDT_ADD_DESCRIPTOR(123);
  IDT_ADD_DESCRIPTOR(124);
  IDT_ADD_DESCRIPTOR(125);
  IDT_ADD_DESCRIPTOR(126);
  IDT_ADD_DESCRIPTOR(127);
  IDT_ADD_DESCRIPTOR(128);
  IDT_ADD_DESCRIPTOR(129);
  IDT_ADD_DESCRIPTOR(130);
  IDT_ADD_DESCRIPTOR(131);
  IDT_ADD_DESCRIPTOR(132);
  IDT_ADD_DESCRIPTOR(133);
  IDT_ADD_DESCRIPTOR(134);
  IDT_ADD_DESCRIPTOR(135);
  IDT_ADD_DESCRIPTOR(136);
  IDT_ADD_DESCRIPTOR(137);
  IDT_ADD_DESCRIPTOR(138);
  IDT_ADD_DESCRIPTOR(139);
  IDT_ADD_DESCRIPTOR(140);
  IDT_ADD_DESCRIPTOR(141);
  IDT_ADD_DESCRIPTOR(142);
  IDT_ADD_DESCRIPTOR(143);
  IDT_ADD_DESCRIPTOR(144);
  IDT_ADD_DESCRIPTOR(145);
  IDT_ADD_DESCRIPTOR(146);
  IDT_ADD_DESCRIPTOR(147);
  IDT_ADD_DESCRIPTOR(148);
  IDT_ADD_DESCRIPTOR(149);
  IDT_ADD_DESCRIPTOR(150);
  IDT_ADD_DESCRIPTOR(151);
  IDT_ADD_DESCRIPTOR(152);
  IDT_ADD_DESCRIPTOR(153);
  IDT_ADD_DESCRIPTOR(154);
  IDT_ADD_DESCRIPTOR(155);
  IDT_ADD_DESCRIPTOR(156);
  IDT_ADD_DESCRIPTOR(157);
  IDT_ADD_DESCRIPTOR(158);
  IDT_ADD_DESCRIPTOR(159);
  IDT_ADD_DESCRIPTOR(160);
  IDT_ADD_DESCRIPTOR(161);
  IDT_ADD_DESCRIPTOR(162);
  IDT_ADD_DESCRIPTOR(163);
  IDT_ADD_DESCRIPTOR(164);
  IDT_ADD_DESCRIPTOR(165);
  IDT_ADD_DESCRIPTOR(166);
  IDT_ADD_DESCRIPTOR(167);
  IDT_ADD_DESCRIPTOR(168);
  IDT_ADD_DESCRIPTOR(169);
  IDT_ADD_DESCRIPTOR(170);
  IDT_ADD_DESCRIPTOR(171);
  IDT_ADD_DESCRIPTOR(172);
  IDT_ADD_DESCRIPTOR(173);
  IDT_ADD_DESCRIPTOR(174);
  IDT_ADD_DESCRIPTOR(175);
  IDT_ADD_DESCRIPTOR(176);
  IDT_ADD_DESCRIPTOR(177);
  IDT_ADD_DESCRIPTOR(178);
  IDT_ADD_DESCRIPTOR(179);
  IDT_ADD_DESCRIPTOR(180);
  IDT_ADD_DESCRIPTOR(181);
  IDT_ADD_DESCRIPTOR(182);
  IDT_ADD_DESCRIPTOR(183);
  IDT_ADD_DESCRIPTOR(184);
  IDT_ADD_DESCRIPTOR(185);
  IDT_ADD_DESCRIPTOR(186);
  IDT_ADD_DESCRIPTOR(187);
  IDT_ADD_DESCRIPTOR(188);
  IDT_ADD_DESCRIPTOR(189);
  IDT_ADD_DESCRIPTOR(190);
  IDT_ADD_DESCRIPTOR(191);
  IDT_ADD_DESCRIPTOR(192);
  IDT_ADD_DESCRIPTOR(193);
  IDT_ADD_DESCRIPTOR(194);
  IDT_ADD_DESCRIPTOR(195);
  IDT_ADD_DESCRIPTOR(196);
  IDT_ADD_DESCRIPTOR(197);
  IDT_ADD_DESCRIPTOR(198);
  IDT_ADD_DESCRIPTOR(199);
  IDT_ADD_DESCRIPTOR(200);
  IDT_ADD_DESCRIPTOR(201);
  IDT_ADD_DESCRIPTOR(202);
  IDT_ADD_DESCRIPTOR(203);
  IDT_ADD_DESCRIPTOR(204);
  IDT_ADD_DESCRIPTOR(205);
  IDT_ADD_DESCRIPTOR(206);
  IDT_ADD_DESCRIPTOR(207);
  IDT_ADD_DESCRIPTOR(208);
  IDT_ADD_DESCRIPTOR(209);
  IDT_ADD_DESCRIPTOR(210);
  IDT_ADD_DESCRIPTOR(211);
  IDT_ADD_DESCRIPTOR(212);
  IDT_ADD_DESCRIPTOR(213);
  IDT_ADD_DESCRIPTOR(214);
  IDT_ADD_DESCRIPTOR(215);
  IDT_ADD_DESCRIPTOR(216);
  IDT_ADD_DESCRIPTOR(217);
  IDT_ADD_DESCRIPTOR(218);
  IDT_ADD_DESCRIPTOR(219);
  IDT_ADD_DESCRIPTOR(220);
  IDT_ADD_DESCRIPTOR(221);
  IDT_ADD_DESCRIPTOR(222);
  IDT_ADD_DESCRIPTOR(223);
  IDT_ADD_DESCRIPTOR(224);
  IDT_ADD_DESCRIPTOR(225);
  IDT_ADD_DESCRIPTOR(226);
  IDT_ADD_DESCRIPTOR(227);
  IDT_ADD_DESCRIPTOR(228);
  IDT_ADD_DESCRIPTOR(229);
  IDT_ADD_DESCRIPTOR(230);
  IDT_ADD_DESCRIPTOR(231);
  IDT_ADD_DESCRIPTOR(232);
  IDT_ADD_DESCRIPTOR(233);
  IDT_ADD_DESCRIPTOR(234);
  IDT_ADD_DESCRIPTOR(235);
  IDT_ADD_DESCRIPTOR(236);
  IDT_ADD_DESCRIPTOR(237);
  IDT_ADD_DESCRIPTOR(238);
  IDT_ADD_DESCRIPTOR(239);
  IDT_ADD_DESCRIPTOR(240);
  IDT_ADD_DESCRIPTOR(241);
  IDT_ADD_DESCRIPTOR(242);
  IDT_ADD_DESCRIPTOR(243);
  IDT_ADD_DESCRIPTOR(244);
  IDT_ADD_DESCRIPTOR(245);
  IDT_ADD_DESCRIPTOR(246);
  IDT_ADD_DESCRIPTOR(247);
  IDT_ADD_DESCRIPTOR(248);
  IDT_ADD_DESCRIPTOR(249);
  IDT_ADD_DESCRIPTOR(250);
  IDT_ADD_DESCRIPTOR(251);
  IDT_ADD_DESCRIPTOR(252);
  IDT_ADD_DESCRIPTOR(253);
  IDT_ADD_DESCRIPTOR(254);
  IDT_ADD_DESCRIPTOR(255);

  /* build the idt selector */
  _idt_load_selector();

  return ERR_NONE;
}


/**
 * _idt_add_descriptor():
 *
 */
static void		_idt_add_descriptor(uint8_t	index,
					    uint32_t	offset,
					    uint16_t	selector,
					    uint16_t	attribs)
{
  /* Reset the IDT entry. */
  _idt[index] = 0ull;

  /* Configure the gate's offset. */
  _idt[index] |= ((offset & MASK_16BITS) | (((uint64_t) offset & 0xffff0000) << 32));

  /* Configure the gate's selector. */
  _idt[index] |= ((uint64_t) selector << 16);

  /* Configure the attributes for this gate descriptor. */
  _idt[index] |= ((uint64_t) attribs << 32);
}


/**
 * _idt_load_selector():
 *
 */
static void		_idt_load_selector(void)
{
  idt_idtr_s		idtr;

  /* Hardbuild the selector. */
  idtr.limit = IDT_N * sizeof (uint64_t);
  idtr.base = (uint32_t) _idt;

  /* Load the GDT register with this selector. */
  lidt(&idtr);
}
